work correctly with newer git versions and with colors turned on

diff --git a/ogit b/ogit
--- a/ogit
+++ b/ogit
@@ -6,20 +6,22 @@ OPTIONS_SPEC=
 
 ref_overlook=refs/overlook
 
+. "$(git --exec-path)/git-sh-setup"
+cd_to_toplevel &&
+
 git rev-parse -q --verify $ref_overlook >/dev/null 2>/dev/null
 HAVE_OVERLOOK=$?
 
 if [ "$HAVE_OVERLOOK" -eq "0" ]; then
-        . git-sh-setup &&
-	cd_to_toplevel &&
-	( git show $ref_overlook -p | patch --reverse > /dev/null ) || die "unapplying overlooked changes failed";
+    DIFF=`git show refs/overlook --pretty=format:"%H..%P"| head -n 1`
+    ( git diff $DIFF -p --no-color | patch -p1 > /dev/null ) || die "unapplying overlooked changes failed";
 fi
 
 git $@
 RETURN=$?
 
 if [ "$HAVE_OVERLOOK" -eq "0" ]; then
-	( git show $ref_overlook -p | patch > /dev/null ) || die "unapplying overlooked changes failed"
+    ( git diff $DIFF -p --no-color | patch -p1 --reverse > /dev/null ) || die "applying overlooked changes failed"
 fi
 
 exit $RETURN
